{% set name = "pytest-celery" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_celery-{{ version }}.tar.gz
  sha256: 7873fb3cf4fbfe9b0dd15d359bdb8bbab4a41c7e48f5b0adb7d36138d3704d52

build:
  number: 0
  # pytest-celery 1.2.1 unresolved on py3.13 due to docker-py<8 & urllib3<2
  skip: true  # [py<=3.8]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - poetry-core >=1.8.1
    - celery
    - pip
  run:
    - python
    - celery
    - kombu
    - tenacity >=9.0.0
    - pytest-docker-tools >=3.1.3
    - docker-py >=7.1.0,<8.0.0
    - psutil >=7.0.0
    - setuptools >=60.0.0,<75.0.0  # [py>=38 and py<39]
    - setuptools >=75.8.0  # [py>=39 and py<4]
    - debugpy >=1.8.12,<2.0.0
  run_constrained:
    - redis-py *
    - python-memcached *
    #-- sqs
    - boto3 *
    - botocore *
    - urllib3 >=1.26.16
    #--

test:
  imports:
    - pytest_celery
    - pytest_celery.api
    - pytest_celery.defaults
    - pytest_celery.fixtures
    - pytest_celery.vendors
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://github.com/celery/pytest-celery
  summary: Pytest plugin for Celery
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: Other
  summary: A library for property based testing
  description: |
     It is pytest plugin designed for Celery application developers.
     It enables dynamic orchestration of Celery environments for testing tasks
     in isolated conditions, leveraging Docker & pytest-docker-tools for environment simulation.
  dev_url: https://github.com/celery/pytest-celery
  doc_url: https://docs.celeryq.dev/projects/pytest-celery

extra:
  recipe-maintainers:
    - igortg
