{% set name = "pytest-celery" %}
{% set version = "1.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
    sha256: bd9e5b0f594ec5de9ab97cf27e3a11c644718a761bab6b997d01800fd7394f64
    # tests from github source
  - url: https://github.com/celery/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: b2d797fd5fe557fc070509683ca8caa06c5bca6eafb4367d96496f0f84db0f04
    folder: gh_src

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<38]

requirements:
  host:
    - python
    - poetry-core >=1.8.1
    - pip
  run:
    - python
    - celery
    - kombu
    - tenacity >=9.0.0
    - pytest-docker-tools >=3.1.3
    - docker-py >=7.1.0,<8.0.0
    - psutil >=7.0.0
    - debugpy >=1.8.12,<2.0.0
  run_constrained:
    - redis-py *
    - python-memcached *
    #-- sqs
    - boto3 *
    - botocore *
    #--

test:
  source_files:
    - gh_src/tests
  imports:
    - pytest_celery
    - pytest_celery.api
    - pytest_celery.defaults
    - pytest_celery.fixtures
    - pytest_celery.vendors
  requires:
    - pip
    - pytest
    - redis-py
    - python-memcached
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - >
      python -c "open('pytest.ini','w').write(
      '[pytest]\n'
      'pythonpath = gh_src\n'
      'python_classes = test*\n'
      'python_files = test_*.py\n'
      'python_functions = test_*\n'
      'testpaths = gh_src/tests/unit\n'
      )"
    - python -m pytest -ra -vv

about:
  home: https://github.com/celery/pytest-celery
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: Other
  summary: Pytest plugin for Celery
  description: |
     It is a pytest plugin designed for Celery application developers.
     It enables dynamic orchestration of Celery environments for testing tasks
     in isolated conditions, leveraging Docker & pytest-docker-tools for environment simulation.
  dev_url: https://github.com/celery/pytest-celery
  doc_url: https://docs.celeryq.dev/projects/pytest-celery

extra:
  recipe-maintainers:
    - igortg
